package com.dingli.commend.dao;

import com.dingli.commend.bean.mMember;
import com.dingli.commend.bean.mMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface mMemberMapper {
	
	List<mMember> selectByMember(mMember m);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    int countByExample(mMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    int deleteByExample(mMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    int insert(mMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    int insertSelective(mMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    List<mMember> selectByExample(mMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    mMember selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") mMember record, @Param("example") mMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    int updateByExample(@Param("record") mMember record, @Param("example") mMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    int updateByPrimaryKeySelective(mMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    int updateByPrimaryKey(mMember record);
}