package com.dingli.commend.bean;

public class Advance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.id
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.title
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.img_file_name
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private String imgFileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.link
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.weight
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private Integer weight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.id
     *
     * @return the value of ad.id
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.id
     *
     * @param id the value for ad.id
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.title
     *
     * @return the value of ad.title
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.title
     *
     * @param title the value for ad.title
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.img_file_name
     *
     * @return the value of ad.img_file_name
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public String getImgFileName() {
        return imgFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.img_file_name
     *
     * @param imgFileName the value for ad.img_file_name
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setImgFileName(String imgFileName) {
        this.imgFileName = imgFileName == null ? null : imgFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.link
     *
     * @return the value of ad.link
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.link
     *
     * @param link the value for ad.link
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.weight
     *
     * @return the value of ad.weight
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.weight
     *
     * @param weight the value for ad.weight
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }
}