package com.dingli.commend.bean;

import java.math.BigDecimal;

public class Business {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.id
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.img_file_name
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private String imgFileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.title
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.subtitle
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private String subtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.price
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.distance
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private Integer distance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.number
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.desc
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private String descsb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.city
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.category
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.star_total_num
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private Integer starTotalNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.comment_total_num
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private Integer commentTotalNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.id
     *
     * @return the value of business.id
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.id
     *
     * @param id the value for business.id
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.img_file_name
     *
     * @return the value of business.img_file_name
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public String getImgFileName() {
        return imgFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.img_file_name
     *
     * @param imgFileName the value for business.img_file_name
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setImgFileName(String imgFileName) {
        this.imgFileName = imgFileName == null ? null : imgFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.title
     *
     * @return the value of business.title
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.title
     *
     * @param title the value for business.title
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.subtitle
     *
     * @return the value of business.subtitle
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.subtitle
     *
     * @param subtitle the value for business.subtitle
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.price
     *
     * @return the value of business.price
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.price
     *
     * @param price the value for business.price
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.distance
     *
     * @return the value of business.distance
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public Integer getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.distance
     *
     * @param distance the value for business.distance
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setDistance(Integer distance) {
        this.distance = distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.number
     *
     * @return the value of business.number
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.number
     *
     * @param number the value for business.number
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.desc
     *
     * @return the value of business.desc
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public String getDescsb() {
        return descsb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.desc
     *
     * @param desc the value for business.desc
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setDescsb(String descsb) {
        this.descsb = descsb == null ? null : descsb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.city
     *
     * @return the value of business.city
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.city
     *
     * @param city the value for business.city
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.category
     *
     * @return the value of business.category
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.category
     *
     * @param category the value for business.category
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.star_total_num
     *
     * @return the value of business.star_total_num
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public Integer getStarTotalNum() {
        return starTotalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.star_total_num
     *
     * @param starTotalNum the value for business.star_total_num
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setStarTotalNum(Integer starTotalNum) {
        this.starTotalNum = starTotalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.comment_total_num
     *
     * @return the value of business.comment_total_num
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public Integer getCommentTotalNum() {
        return commentTotalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.comment_total_num
     *
     * @param commentTotalNum the value for business.comment_total_num
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setCommentTotalNum(Integer commentTotalNum) {
        this.commentTotalNum = commentTotalNum;
    }
}