package com.dingli.commend.bean;

public class Dictype extends DictypeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic.name
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic.weight
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private Integer weight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic.name
     *
     * @return the value of dic.name
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic.name
     *
     * @param name the value for dic.name
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic.weight
     *
     * @return the value of dic.weight
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic.weight
     *
     * @param weight the value for dic.weight
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }
}