package com.dingli.commend.bean;

import java.math.BigDecimal;
import java.util.Date;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.business_id
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.member_id
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.num
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.comment_state
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private Integer commentState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.price
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.create_time
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.business_id
     *
     * @return the value of orders.business_id
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.business_id
     *
     * @param businessId the value for orders.business_id
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.member_id
     *
     * @return the value of orders.member_id
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.member_id
     *
     * @param memberId the value for orders.member_id
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.num
     *
     * @return the value of orders.num
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.num
     *
     * @param num the value for orders.num
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.comment_state
     *
     * @return the value of orders.comment_state
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public Integer getCommentState() {
        return commentState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.comment_state
     *
     * @param commentState the value for orders.comment_state
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setCommentState(Integer commentState) {
        this.commentState = commentState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.price
     *
     * @return the value of orders.price
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.price
     *
     * @param price the value for orders.price
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.create_time
     *
     * @return the value of orders.create_time
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.create_time
     *
     * @param createTime the value for orders.create_time
     *
     * @mbggenerated Wed Aug 15 16:30:44 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}